const songs = [


    {
        name: "Last Christmas",
        tempo: 108,
        notes: [
            ["Last", "Christmas,", "I", "gave", "you", "my", "heart"],
            ["But", "the", "very", "next", "day,", "you", "gave", "it", "away"],
            ["This", "year,", "to", "save", "me", "from", "tears"],
            ["I'll", "give", "it", "to", "someone", "special"],
        ],
        pauses: [
            [1, 1.5, 2, 0.5, 0.5, 0.5, 0.5],
            [1.5, 0.5, 0.5, 1, 1, 1.5, 0.5, 0.5, 0.5],
            [2.5, 1.5, 2, 0.5, 0.5, 0.5, 0.5],
            [2, 0.5, 0.5, 0.5, 0.5, 2],
        ],
    },
    {
        name: "All I Want for Christmas",
        tempo: 150,
        notes: [
            ["I", "don't", "want", "a", "lot", "for", "Christmas"],
            ["There", "is", "just", "one", "thing", "I", "need"],
            ["I", "don't", "care", "about", "the", "presents"],
            ["underneath", "the", "Christmas", "tree"],
            ["I", "just", "want", "you", "for", "my", "own"],
            ["More", "than", "you", "could", "ever", "know"],
            ["Make", "my", "wish", "come", "true"],
            ["All", "I", "want", "for", "Christmas", "is", "you"],
        ],
        pauses: [
            [1, 1, 1, 1, 1, 1, 1],
            [2, 1, 1, 1, 1, 1, 1],
            [2, 1, 1, 1, 2, 1],
            [2, 3, 1, 2],
            [2, 1, 1, 1, 1, 1, 1],
            [2, 1, 1, 1, 1, 2],
            [2, 1, 1, 1, 1],
            [2, 1, 1, 1, 1, 2, 1],
        ],
    },
    {
        name: "O Come All Ye Faithfull",
        tempo: 114,
        notes: [
            ["Oh", "come", "all", "ye", "faithful,"],
            ["Joyful", "and", "triumphant"],
            ["Oh", "come", "ye", "Oh", "come", "ye"],
            ["to", "Bethlehem"],
            ["Come", "and", "behold", "him"],
            ["Born", "the", "king", "of", "angels"],
            ["Oh", "come", "let", "us", "adore", "him"],
            ["Oh", "come", "let", "us", "adore", "him"],
            ["Oh", "come", "let", "us", "adore", "him"],
            ["Christ", "the", "Lord"],
        ],
        pauses: [
            [1, 1, 2, 1, 1],
            [4, 2, 1],
            [4, 1, 2, 1, 1, 2],
            [1, 1],
            [8, 2, 1, 3],
            [2, 1, 1, 1, 1],
            [3, 1, 1, 1, 1, 3],
            [1, 1, 1, 1, 1, 3],
            [1, 1, 1, 1, 1, 3],
            [2, 3, 1],
        ],
    },
    {
        name: "I'm Dreaming of a White Christmas",
        tempo: 118,
        notes: [
            ["I'm", "dreaming", "of", "a", "white", "Christmas"],
            ["Just", "like", "the", "ones", "I", "used", "to", "know"],
            ["Where", "the", "tree", "tops", "glisten"],
            ["and", "children", "listen"],
            ["to", "hear", "sleigh", "bells", "in", "the", "snow"],
        ],
        pauses: [
            [1, 4, 2, 1, 1, 4],
            [5, 1, 1, 1, 1, 1, 1, 1],
            [6, 1, 1, 2, 2],
            [3, 1, 4],
            [3, 1, 4, 1, 1, 1, 1],
        ],
    },

    {
        name: "Silent Night",
        tempo: 61,
        notes: [
            ["Silent", "Night,", "Holy", "Night"],
            ["All", "is", "calm,", "all", "is", "bright"],
            ["Round", "yon", "virgin", "and", "her", "child."],
            ["Holy", "infant", "tender", "and", "mild"],
            ["Sleep", "in", "heavenly", "peace"],
            ["Sleep", "in", "heavenly", "peace"],
        ],
        pauses: [
            [2, 1.5, 1.5, 1.5],
            [1.5, 1, 0.5, 1.5, 1, 0.5],
            [1.5, 1, 0.5, 1.5, 1, 0.5],
            [1.5, 1.5, 1.5, 1, 0.5],
            [1.5, 1, 0.5, 1.5],
            [3, 1, 0.5, 1.5],
        ],
    },
    {
        name: "Merry Christmas Everybody",
        tempo: 126,
        notes: [
            [
                "Are",
                "you",
                "hanging",
                "up",
                "a",
                "stocking",
                "on",
                "your",
                "wall",
            ],
            [
                "It's",
                "the",
                "time",
                "that",
                "every",
                "Santa",
                "has",
                "a",
                "ball",
            ],
            ["Does", "he", "ride", "a", "red", "nosed", "reindeer"],
            ["Do", "a", "ton-up", "on", "his", "sleigh"],
            [
                "Do",
                "the",
                "fairies",
                "keep",
                "him",
                "sober",
                "for",
                "a",
                "day?",
            ],
        ],
        pauses: [
            [0.5, 0.5, 0.5, 2, 1, 1, 2, 1, 1],
            [7, 0.5, 0.5, 1, 1, 2, 2, 1, 1],
            [7, 0.5, 0.5, 1, 1, 1, 1],
            [3, 0.5, 0.5, 2, 1, 1],
            [3, 0.5, 0.5, 2, 1, 1, 2, 1, 1],
        ],
    },

    {
        name: "Mary's Boy Child",
        tempo: 113,
        notes: [
            ["Long", "time", "ago", "in", "Bethlehem"],
            ["so", "the", "holy", "bible", "say"],
            ["Mary's", "boy", "child,", "Jesus", "Christ"],
            ["was", "born", "on", "Christmas", "Day."],
            ["Hark,", "now", "hear", "the", "angels", "sing,"],
            ["a", "new", "born", "king", "today"],
            ["and", "man", "will", "live", "forever", "more"],
            ["because", "of", "Christmas", "Day"],
        ],
        pauses: [
            [1, 1, 1, 2, 1],
            [3, 0.5, 0.5, 2, 2],
            [4, 2, 1, 1.5, 2],
            [1.5, 0.5, 1, 1, 2],
            [4, 1, 1, 1, 1, 2],
            [2, 1, 1, 1, 1],
            [4, 1, 1, 1, 1, 3],
            [2, 2, 1, 2],
        ],
    },

    {
        name: "Hark the Herald",
        tempo: 114,
        notes: [
            ["Hark,", "the", "herald", "angels", "sing"],
            ["Glory", "to", "the", "new", "born", "king"],
            ["Peace", "on", "Earth", "and", "mercy", "mild"],
            ["God", "and", "sinners", "reconciled"],
            ["Joyful", "all", "ye", "nations", "rise"],
            ["Join", "the", "triumph", "of", "the", "skies"],
            ["with", "the", "angelic", "host", "proclaim"],
            ["Christ", "is", "born", "in", "Bethlehem"],
            ["Hark,", "the", "herald", "angels", "sing"],
            ["Glory", "to", "the", "new", "born", "king"],
        ],
        pauses: [
            [1, 1, 1, 2, 2],
            [2, 2, 1.5, 0.5, 1, 1],
            [2, 1, 1, 1.5, 0.5, 2],
            [2, 1, 1, 2],
            [4, 2, 1, 1, 2],
            [2, 1, 1, 2, 1, 1],
            [2, 1, 0.1, 2.9, 1],
            [3, 1, 1, 1.5, 0.5],
            [4, 1.5, 0.5, 2, 2],
            [2, 2, 1.5, 0.5, 1, 1],
        ],
    },

    {
        name: "Happy Christmas (War is Over)",
        tempo: 146,
        notes: [
            ["So", "this", "is", "Christmas"],
            ["and", "what", "have", "you", "done?"],
            ["Another", "year", "over"],
            ["a", "new", "one", "just", "begun"],
            ["and", "so", "this", "is", "Christmas"],
            ["I", "hope", "you", "have", "fun,"],
            ["the", "near", "and", "the", "dear", "ones,"],
            ["the", "old", "and", "the", "young."],
        ],
        pauses: [
            [1, 1, 1, 1],
            [8, 1, 1, 1, 1],
            [8, 3, 1],
            [8, 1, 1, 1, 0.5, 0.5],
            [8, 1, 1, 1, 1],
            [8, 1, 1, 1, 1],
            [8, 1, 1, 1, 1, 1],
            [8, 1, 1, 1, 1],
        ],
    },
    {
        name: "Jingle Bells",
        tempo: 122,
        notes: [
            ["Jingle", "bells", "jingle", "bells"],
            ["Jingle", "all", "the", "way"],
            ["Oh", "what", "fun", "it", "is", "to", "ride"],
            ["on", "a", "one", "horse", "open", "sleigh."],
            ["Oh", "Jingle", "bells", "jingle", "bells"],
            ["Jingle", "all", "the", "way"],
            ["Oh", "what", "fun", "it", "is", "to", "ride"],
            ["on", "a", "one", "horse", "open", "sleigh."],
        ],
        pauses: [
            [1, 1, 1, 1],
            [1, 1, 0.5, 0.5],
            [2.5, 0.5, 0.5, 1, 0.25, 0.25, 0.5],
            [1, 0.25, 0.25, 0.5, 0.5, 1],
            [1, 1, 1, 1, 1],
            [1, 1, 0.5, 0.5],
            [2.5, 0.5, 0.5, 1, 0.25, 0.25, 0.5],
            [1, 0.25, 0.25, 0.5, 0.5, 1],
        ],
    },
    {
        name: "Good King Wenceslas",
        tempo: 153,
        notes: [
            ["Good", "King", "Wenceslas", "looked", "out"],
            ["On", "the", "feast", "of", "Stephen"],
            ["When", "the", "snow", "lay", "roundabout"],
            ["Deep", "and", "crisp", "and", "even"],
            ["Brightly", "shone", "the", "moon", "that", "night"],
            ["though", "the", "frost", "was", "cruel"],
            ["When", "the", "poor", "man", "came", "in", "sight"],
            ["Gathering", "winter", "fuel"],
        ],
        pauses: [
            [3, 1, 1, 3, 1],
            [2, 1, 1, 1, 1],
            [4, 1, 1, 1, 1],
            [4, 1, 1, 1, 1],
            [4, 2, 1, 1, 1, 1],
            [2, 1, 1, 1, 1],
            [4, 1, 1, 1, 1, 1, 1],
            [2, 2, 2],
        ],
    },
    {
        name: "We Wish You a Merry Christmas",
        tempo: 120,
        notes: [
            ["We", "wish", "you", "a", "merry", "christmas"],
            ["We", "wish", "you", "a", "merry", "christmas"],
            ["We", "wish", "you", "a", "merry", "christmas"],
            ["and", "a", "happy", "new", "year"],
        ],
        pauses: [
            [1, 1, 1, 0.5, 0.5, 1],
            [2, 1, 1, 0.5, 0.5, 1],
            [2, 1, 1, 0.5, 0.5, 1],
            [2, 0.5, 0.5, 2, 1, 1],
        ],
    },
    {
        name: "Once in Royal David's City",
        tempo: 101,
        notes: [
            ["Once ", "in ", "royal ", "David's ", "city,"],
            ["Stood", "a", "lowley", "cattle", "shed"],
            ["Where", "a", "mother", "laid", "her", "baby"],
            ["In", "a", "manger", "for", "his", "bed"],
            ["Mary", "was", "that", "mother,", "mild,"],
            ["Jesus", "Christ,", "her", "little", "child."],
        ],
        pauses: [
            [0, 1, 1, 2, 2],
            [2, 1, 1, 2, 2],
            [2, 1, 1, 2, 1, 1],
            [2, 1, 1, 2, 1, 1],
            [2, 2, 1.5, 0.5, 2],
            [2, 2, 1.5, 0.5, 2],
        ],
    },
    {
        name: "While Shepherds Watched Their Flocks",
        tempo: 101,
        notes: [
            ["While", "shepherds", "watched", "their", "flocks", "by", "night"],
            ["all", "seated", "on", "the", "ground"],
            ["The", "Angel", "of", "the", "Lord", "came", "down"],
            ["and", "glory", "shone", "around"],
        ],
        pauses: [
            [1, 1, 2, 1, 1, 1, 1],
            [1, 1, 2, 1, 1],
            [2, 1, 2, 1, 1, 1, 1],
            [1, 1, 2, 1, 2.1, 1],
        ],
    },
        // {
    //     name: "Do They Know It's Christmas?",
    //     tempo: 112,
    //     notes: [
    //         ["It's", "Christmas", "time,"],
    //         ["there's", "no", "need", "to", "be", "afraid"],
    //         ["At", "Christmas", "time,"],
    //         ["we", "let", "in", "light", "and", "we", "banish", "shade"],
    //         ["And", "in", "our", "world", "of", "plenty"],
    //         ["we", "can", "spread", "a", "smile", "of", "joy"],
    //         ["Throw", "your", "arms", "around", "the", "world"],
    //         ["at", "Christmas", "time"]
    //     ],
    //     pauses: [
    //         [1, 0.5, 1.5],
    //         [3,0.5, 0.5, 0.5,0.5, 0.25],
    //         [2.5, 0.5, 1.5],
    //         [3, 0.5,0.5, 1, 1, 0.5, 0.5,1],
    //         [4.5]
    //     ],
    // },
];

export default songs;
